#define MINIAUDIO_IMPLEMENTATION
#include "miniaudio.h"
#include "AudioPlayer.h"
#include <algorithm>
AudioPlayer::AudioPlayer()=default;
AudioPlayer::~AudioPlayer(){std::lock_guard<std::mutex>l(mutex_);if(sound_){ma_sound_uninit(sound_);delete sound_;}if(engine_){ma_engine_uninit(engine_);delete engine_;}}
bool AudioPlayer::initialize(){std::lock_guard<std::mutex>l(mutex_);engine_=new ma_engine{};if(ma_engine_init(nullptr,engine_)!=MA_SUCCESS){delete engine_;engine_=nullptr;return false;}ma_engine_set_volume(engine_,volume_);return true;}
bool AudioPlayer::load(const Song&s){std::lock_guard<std::mutex>l(mutex_);if(!engine_)return false;if(sound_){ma_sound_uninit(sound_);delete sound_;sound_=nullptr;}sound_=new ma_sound{};if(ma_sound_init_from_file(engine_,s.filePath.c_str(),MA_SOUND_FLAG_NO_PITCH|MA_SOUND_FLAG_NO_SPATIALIZATION,nullptr,nullptr,sound_)!=MA_SUCCESS){delete sound_;sound_=nullptr;return false;}currentSong_=s;return true;}
void AudioPlayer::play(){std::lock_guard<std::mutex>l(mutex_);if(sound_)ma_sound_start(sound_);}void AudioPlayer::pause(){std::lock_guard<std::mutex>l(mutex_);if(sound_)ma_sound_stop(sound_);}void AudioPlayer::stop(){std::lock_guard<std::mutex>l(mutex_);if(sound_){ma_sound_stop(sound_);ma_sound_seek_to_pcm_frame(sound_,0);}}
void AudioPlayer::seek(double seconds){std::lock_guard<std::mutex>l(mutex_);if(!sound_)return;float df=0; double d=(ma_sound_get_length_in_seconds(sound_,&df)==MA_SUCCESS?df:currentSong_.duration); seconds=std::clamp(seconds,0.0,d>0?d:seconds);auto sr=ma_engine_get_sample_rate(engine_);ma_sound_seek_to_pcm_frame(sound_,(ma_uint64)(seconds*sr));}
void AudioPlayer::setVolume(float v){std::lock_guard<std::mutex>l(mutex_);volume_=std::clamp(v,0.0f,1.0f);if(engine_)ma_engine_set_volume(engine_,volume_);}
bool AudioPlayer::isPlaying()const{std::lock_guard<std::mutex>l(mutex_);return sound_&&ma_sound_is_playing(sound_);}bool AudioPlayer::isFinished()const{std::lock_guard<std::mutex>l(mutex_);if(!sound_)return false;float p=0,d=0;if(ma_sound_get_cursor_in_seconds(sound_,&p)!=MA_SUCCESS||ma_sound_get_length_in_seconds(sound_,&d)!=MA_SUCCESS)return false;return d>0&&p>=d-0.15&&!ma_sound_is_playing(sound_);}double AudioPlayer::position()const{std::lock_guard<std::mutex>l(mutex_);if(!sound_)return 0;float p=0;ma_sound_get_cursor_in_seconds(sound_,&p);return p;}double AudioPlayer::duration()const{std::lock_guard<std::mutex>l(mutex_);if(!sound_)return currentSong_.duration;float d=0;return ma_sound_get_length_in_seconds(sound_,&d)==MA_SUCCESS?d:currentSong_.duration;}
